pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 必须加在这里！！！
        //maven { url "https://mirrors.tencent.com/repository/maven/" }
        // 我给你的这两个 加在这里！！！
        maven { url "https://repo1.maven.org/maven2" }
        maven { url "https://oss.sonatype.org/content/groups/public" }
    }
}
rootProject.name = "TravelBook"
include ':app'
